apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    io.kompose.service: social-graph-redis
  name: social-graph-redis
spec:
  serviceName: "social-graph-redis"
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: social-graph-redis
  volumeClaimTemplates:
  - metadata:
      name: social-graph-redis
      annotations:
        volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi 
  template:
    metadata:
     labels:
       io.kompose.service: social-graph-redis
    spec:
     nodeSelector:
        kubernetes.io/hostname: data-node
     serviceAccount: nfs-provisioner
     containers:
      - image: redis
        imagePullPolicy: IfNotPresent
        name: social-graph-redis
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /var/lib/redis
          name: social-graph-redis
     hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        #- "media-filter-service.default.svc.cluster.local"
        - "social-graph-redis"
