apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: compose-post-redis
  name: compose-post-redis
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: compose-post-redis
  template:
    metadata:
      labels:
        io.kompose.service: compose-post-redis
    spec:
      nodeSelector:
        kubernetes.io/hostname: data-node
      containers:
      - command:
        - sh
        - -c
        - "rm -f /data/dump.rdb && redis-server --save \"\" --appendonly no"
        image: redis
        imagePullPolicy: IfNotPresent
        name: compose-post-redis
        ports:
        - containerPort: 6379
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        #- "media-filter-service.default.svc.cluster.local"
        - "compose-post-redis"
     

        






