apiVersion: v1
kind: Service
metadata:
  name: compose-post-redis
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    io.kompose.service: compose-post-redis
  type: ClusterIP 
  #clusterIP: None
