apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: text-filter-service
  name: text-filter-service
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: text-filter-service
  template:
    metadata:
      labels:
        io.kompose.service: text-filter-service
    spec:
      nodeSelector:
        kubernetes.io/hostname: work-node
      # securityContext:
      #   runAsNonRoot: true
      #   runAsUser: 1000321000
      # initContainers:
      # - name: configwriter
      #   securityContext:    
      #     runAsNonRoot: true
      #   env:
      #   - name: LOGICNODEIP
      #     value: 172.16.84.130
      #   - name: DATANODEIP
      #     value: 172.16.84.128
      #   image: youngpig/configwriter:latest
      #   imagePullPolicy: IfNotPresent
      #   volumeMounts:
      #   - name: varconfig
      #     mountPath: /var/configFiles
      containers:
      - image: yz2297/social-network-text-filter
        imagePullPolicy: IfNotPresent
        name: text-filter-service
        # lifecycle:
        #   postStart:
        #     exec:
        #       command: ["/bin/sh", "-c", "sleep 5"]
        # securityContext:
        #   runAsNonRoot: true
        volumeMounts:
        - mountPath: /social-network-microservices/config
          name: varconfig
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "text-filter-service"
        #- "text-filter-service.default.svc.cluster.local"
      restartPolicy: Always
      volumes:
      - name: varconfig
        hostPath:
          path: /root/Go-projects/social-Network/SocialNetInComputeFork8s/config


        
