apiVersion: v1
kind: Service
metadata:
  name: media-filter-service
spec:
  ports:
    - port: 40000
      protocol: TCP
      targetPort: 40000
  selector:
    io.kompose.service: media-filter-service
  type: ClusterIP 
  #clusterIP: None
