apiVersion: v1
kind: Service
metadata:
  name: media-service
spec:
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    io.kompose.service: media-service
  type: ClusterIP 