apiVersion: v1
kind: Service
metadata:
  name: user-timeline-mongodb
spec:
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    io.kompose.service: user-timeline-mongodb
  type: ClusterIP
  clusterIP: None 
