apiVersion: v1
kind: Service
metadata:
  name: write-home-timeline-rabbitmq
spec:
  ports:
    - port: 5672
      protocol: TCP
      targetPort: 5672
  selector:
    io.kompose.service: write-home-timeline-rabbitmq
  type: ClusterIP 
  #clusterIP: None
