apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    io.kompose.service: social-graph-mongodb
  name: social-graph-mongodb
spec:
  serviceName: "social-graph-mongodb"
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: social-graph-mongodb
  volumeClaimTemplates:
  - metadata:
      name: social-graph-mongodb
      annotations:
        volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi 
  template:
    metadata:
     labels:
       io.kompose.service: social-graph-mongodb
    spec:
     nodeSelector:
        kubernetes.io/hostname: data-node
     serviceAccount: nfs-provisioner
     containers:
      - image: mongo
        imagePullPolicy: IfNotPresent
        name: social-graph-mongodb
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: /data/db
          name: social-graph-mongodb
     hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        #- "media-filter-service.default.svc.cluster.local"
        - "social-graph-mongodb"
