apiVersion: v1
kind: Service
metadata:
  name: post-storage-memcached
spec:
  ports:
    - port: 11211
      protocol: TCP
      targetPort: 11211
  selector:
    io.kompose.service: post-storage-memcached
  type: ClusterIP
  #clusterIP: None 
