apiVersion: v1
kind: Service
metadata:
  name: user-timeline-service
spec:
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    io.kompose.service: user-timeline-service
  type: ClusterIP 
  #clusterIP: None
