version: "3"
services:

  # Resolving container hostnames from host machine
  # CAUTION: could affect host machine networking
#  dns-social-network:
#    image: defreitas/dns-proxy-server
#    volumes:
#      - /opt/dns-proxy-server/conf:/app/conf
#      - /var/run/docker.sock:/var/run/docker.sock
#      - /etc/resolv.conf:/etc/resolv.conf



  url-shorten-service:
    image: yz2297/social-network-ml-swarm
    hostname: url-shorten-service
    container_name: social-ml-url-shorten-service
    entrypoint: UrlShortenService
#    ports:
#      - 10004:9090
    restart: always

  user-service:
    image: yz2297/social-network-ml-swarm
    hostname: user-service
    container_name: social-ml-user-service
#    ports:
#      - 10005:9090
    restart: always
    entrypoint: UserService
    depends_on:
      - user-memcached
      - user-mongodb



  media-service:
    image: yz2297/social-network-ml-swarm
    hostname: media-service
    container_name: social-ml-media-service
#    ports:
#      - 10006:9090
    restart: always
    entrypoint: MediaService



  text-service:
    image: yz2297/social-network-ml-swarm
    hostname: text-service
    container_name: social-ml-text-service
#    ports:
#      - 10007:9090
    restart: always
    entrypoint: TextService
    depends_on:
     - user-mention-service
     - url-shorten-service

  text-filter-service:
    image: yz2297/social-network-text-filter
    hostname: text-filter-service
    container_name: social-ml-text-filter-service
    # ports:
    #   - 40000:40000
    restart: always

  media-filter-service:
    image: yz2297/social-network-media-filter
    hostname: media-filter-service
    container_name: social-ml-media-filter-service
    # ports:
    #   - 40000:40000
    restart: always

  unique-id-service:
    image: yz2297/social-network-ml-swarm
    hostname: unique-id-service
    container_name: social-ml-unique-id-service
#    ports:
#      - 10008:9090
    restart: always
    entrypoint: UniqueIdService

  user-mention-service:
    image: yz2297/social-network-ml-swarm
    hostname: user-mention-service
    container_name: social-ml-user-mention-service
#    ports:
#      - 10009:9090
    restart: always
    entrypoint: UserMentionService



  nginx-thrift:
    image: yg397/openresty-thrift:xenial
    hostname: nginx-thrift
    container_name: social-ml-nginx-thrift
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ./nginx-web-server/lua-scripts:/usr/local/openresty/nginx/lua-scripts
      - ./nginx-web-server/pages:/usr/local/openresty/nginx/pages
      - ./nginx-web-server/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./nginx-web-server/jaeger-config.json:/usr/local/openresty/nginx/jaeger-config.json
      - ./gen-lua:/gen-lua
      # - /home/yz2297/Software/socialNetwork-ml-swarm/nginx-web-server/lua-scripts:/usr/local/openresty/nginx/lua-scripts
      # - /home/yz2297/Software/socialNetwork-ml-swarm/nginx-web-server/pages:/usr/local/openresty/nginx/pages
      # - /home/yz2297/Software/socialNetwork-ml-swarm/nginx-web-server/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      # - /home/yz2297/Software/socialNetwork-ml-swarm/nginx-web-server/jaeger-config.json:/usr/local/openresty/nginx/jaeger-config.json
      # - /home/yz2297/Software/socialNetwork-ml-swarm/gen-lua:/gen-lua
    depends_on:
      - user-service
      - user-mention-service
      - media-service
      - text-service
      - unique-id-service
      - url-shorten-service
      - home-timeline-service
      - write-user-timeline-service
      - write-home-timeline-service



