apiVersion: v1
kind: Service
metadata:
  name: nginx-thrift
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 31080
  selector:
    io.kompose.service: nginx-thrift
  type: NodePort 
