apiVersion: v1
kind: Service
metadata:
  name: user-timeline-redis
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    io.kompose.service: user-timeline-redis
  type: ClusterIP 
  #clusterIP: None
