apiVersion: v1
kind: Service
metadata:
  name: url-shorten-service
spec:
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    io.kompose.service: url-shorten-service 
  type: ClusterIP
  #clusterIP: None 
