apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: post-storage-memcached
  name: post-storage-memcached
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: post-storage-memcached
  template:
    metadata:
      labels:
        io.kompose.service: post-storage-memcached
    spec:
      nodeSelector:
        kubernetes.io/hostname: data-node
      containers:
      - env:
        - name: MEMCACHED_CACHE_SIZE
          value: "4096"
        - name: MEMCACHED_THREADS
          value: "8"
        image: memcached:1.6.0
        imagePullPolicy: IfNotPresent
        name: post-storage-memcached
        ports:
        - containerPort: 11211
      restartPolicy: Always
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        #- "media-filter-service.default.svc.cluster.local"
        - "post-storage-memcached"
