apiVersion: v1
kind: Service
metadata:
  name: user-memcached
spec:
  ports:
    - port: 11211
      protocol: TCP
      targetPort: 11211
  selector:
    io.kompose.service: user-memcached
  type: ClusterIP 
  #clusterIP: None
