apiVersion: v1
kind: Service
metadata:
  name: unique-id-service
spec:
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    io.kompose.service: unique-id-service
  type: ClusterIP
  #clusterIP: None 
