apiVersion: v1
kind: Service
metadata:
  name: home-timeline-redis
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    io.kompose.service: home-timeline-redis
  type: ClusterIP
  #clusterIP: None 
